[workspace]
members = ["minegrid"]

[workspace.package]
authors = ["Gabriel Martinez <reitaka@gmail.com>"]

[package]
name = "rust-mines"
version = "0.0.1"
edition = "2015"
authors.workspace = true

[dependencies]
minegrid = { version = "0.1", path = "./minegrid" }
